### ISSUE TITLE
Play Instructions

### ISSUE THREAD

**Issue by ghost** [SoyGema/Startcraft_pysc2_minigames#2]
How would non-coders play your mini-game? I can not find instructions in wiki or readme file.

**Comment by SoyGema** [comment]
Hi @IBLoud ,
For executing Starcraft mini-games you need to have  : 

* Starcraft installed in your computer
* Install pysc2 library following the instructions in https://github.com/deepmind/pysc2
* Clone/Download this repository and put ForceField map on map folder 
* Execute the agent from your console typing : 
$ python -m pysc2.bin.agent --map ForceField

Note that you don´t need to code but to access to the terminal with the requirements installed
Please, if you have any doubts let me know 
^^! Thanks for writing . I am actually adding this information to the repository readme.md info

**Comment by SoyGema** [comment]
Hi @IBLoud was this information useful enough to respond your question?
Let me know if I could add something in order to solve any more doubts regarding this topic . ^^

**Comment by ghost** [comment]
The information is fine. I am providing this resource in case you might find need of it: https://developer.ibm.com/tv/dwlive005-replay-use-data-science-to-up-your-game-performance/
