### ISSUE TITLE
Editing mini games

### ISSUE THREAD

**Issue by sumitsk** [SoyGema/Startcraft_pysc2_minigames#4]
Hi,
I want to use some of your minimaps in my research but with some customization like changing the number of units in the team, adding different units and so on. I believe this can be done by editing the .SC2Map file. Is that right? If so, how can i edit those files in linux? Any help is appreciated.

**Comment by SoyGema** [comment]
Hi sumitsk . Thanks for writing and dedicate some time to dig in the community mini-games about pySC2.
You can edit those files with the Starcraft Map editor 
In my case , is in Aplications>StarCraft II>StarCraft II Editor
It should be Inside your StarCraft II folder and has the icon is shaped like this 
<img width="126" alt="captura de pantalla 2018-05-11 a las 13 13 15" src="https://user-images.githubusercontent.com/24204714/39921980-41b7c68e-551d-11e8-8f27-c3be29821a95.png">

Once you get there, you might find a visual interface . Please visit this doc for the ongoing tutorial I am building . With your permission, I will add the suggestions to the tutorial .
https://github.com/SoyGema/Startcraft_pysc2_minigames/tree/master/docs

Go to the trigger menu . Click on the top right part where you might find the wheel bellow 
<img width="50" alt="captura de pantalla 2018-05-11 a las 13 20 46" src="https://user-images.githubusercontent.com/24204714/39922197-3ce966fc-551e-11e8-9f30-95e9541a1ac1.png">


- For changing the units and number of units , in the init script , you can change them by selected in the violet lines . In this case I have s screenshot of the mini-game force field 
<img width="905" alt="captura de pantalla 2018-05-11 a las 13 16 41" src="https://user-images.githubusercontent.com/24204714/39922072-a24ebd4a-551d-11e8-90ee-f921a3c7708e.png">


- In the script "Score Updates and Victory" you might want to change  the reward coming from each episode. 

Please, let me know your advancement towards this topic . You can also PR your mini game to the community repository I am building https://github.com/SoyGema/pySC2_minigames


gl & hf!

**Comment by sumitsk** [comment]
Hi,
I am using StarCraft II Starter Pack. When I am trying to load and edit .SC2MAP files using StarCraft II Editor, I get this message:

Dependency data could not be loaded. Heart of the Swarm license is needed to load required dependencies. Legacy of the void license is needed to load required dependencies.

Any ideas on how to resolve this or is it not possible to edit sc2map files using the starter pack?

**Comment by JoSeTe4ever** [comment]
Due to particularities of the units used on the pocs, I am afraid that you would need the latest version of Starcraf II (Legacy of the void) to edit the mini-maps.

**Comment by SoyGema** [comment]
Hi there ,
Thanks for taking part of the issue @JoSeTe4ever . 👍 
@sumitsk I am afraid I don't control licensing from the Starter Pack as I do hold a game license . However, I think your issue might be related to patch actualization and more people have experienced some problems [here](https://us.battle.net/forums/en/sc2/topic/20742956020) 

My recommendation at this point is at least to try with the proposed forum solutions drafted in battlenet and  if you aren't able to solve it, It might be a nice think to get back to the #pySC2 team . You can reach them in pysc2@deepmind.com and inform of the evolution of your search towards editing SC2 map files.

Please,  let me know If I can help you with something else .
Thanks
gl and hf!
^^

**Comment by stevenbinhu21** [comment]
Hi,
Thanks very much for the markdown and your minigame repo. I am able to alter the mingame maps via the editor and create new maps. However, when loading the new maps to pysc2 testing, the map is empty and all units are gone. I just wonder if there are more steps to just placing the edited maps to the map folder and run testing. Is there some kind of configuration to be done? 
And another question(may sound stupid), I was using the windows version of editor, and test the map in linux headless version game, could there be some kind of compatibility issue?

**Comment by stevenbinhu21** [comment]
Hi,
Thanks very much for the markdown and your minigame repo. I am able to alter the mingame maps via the editor and create new maps. However, when loading the new maps to pysc2 testing, the map is empty and all units are gone. I just wonder if there are more steps to just placing the edited maps to the map folder and run testing. Is there some kind of configuration to be done?
And another question(may sound stupid), I was using the windows version of editor, and test the map in linux headless version game, could there be some kind of compatibility issue?

**Comment by stevenbinhu21** [comment]
Just to add a bit more details, I made some changes to the DefeatRoaches map, and created a bunch of new units. The map works fine when testing in game editor and PySC2 on Windows .  But in ubuntu's version, the pysc2 rendered map is empty. I guess I should find a Linux version editor?  or using the MacOS version?

**Comment by SoyGema** [comment]
Hi @stevenbinhu21 Thanks for taking part of the mini-games thread  

- Have you tried to test the map inside the SC2 editor in both Win and linux ? 
In the top bar, right corner , you might find this shape >> . If you click on it a menu will appear. You might click then in Test document ( I assume this is what you meant in Test in map editor and this step currently works for you in Win and linux ) 
<img width="317" alt="captura de pantalla 2018-05-18 a las 10 08 22" src="https://user-images.githubusercontent.com/24204714/40223600-ebda6fe8-5a83-11e8-9341-3a1da84483b4.png">

- When you say "when loading the new maps to pysc2 testing " , do you mean the step of executing on your console something like 
`my-computer:~ me$ python -m pysc2.bin.agent --map StevenMap`  ??
           
Here are some actions I assume you've done correctly 
1.  Sometimes the **folder Maps is not there by default**, so you might have to create it . Be sure the map is located in the path /Applications/StarCraft II/Maps/mini_games/
2. Go to **pysc2\maps\mini_games.py** and add to mini-games array the mini-gams name 'StevenMap' ? 

- Why are you building it in windows and testing in linux ? have you tried building-testing in the same OS ? 

- Can I ask you for something too ? Would you mind to list in general the types of changes you have make to the mini-game so I might add it to the markdown for others to do it  ? 
Ex ; 

1.  Change or add  Units ( in loop or listed )
2. Change reward system 
3. Change restart 

If you could also tell me something that would be more clear or better explained in the markdown I would also thank you, as it came for me to reach the milestone "get feedback"

Of course, I will like to invite you to PR your mini-game map to a community repo I am building ^^
https://github.com/SoyGema/pySC2_minigames

**Comment by stevenbinhu21** [comment]
@SoyGema  Thanks very much for the quick response and suggestions. I tried the test documents both on Windows and MacOSX version editor and PySC2 testing("python -m pysc2.bin.play --map MapName"), and the map (I created based on DefeatRoaches by just adding 2 more marines at Init and Reset in the Trigger script) works.  However, this map won't render any units when testing with PySC2 in Ubuntu 14.04. The game package is from Blizzard's linux release 3.16.1: [Blizzard Linux Package](https://github.com/Blizzard/s2client-proto#downloads). So I am assuming I need a linux version game editor to get the map working? But the linux package is not equipped with an editor? 

(I wonder how Deepmind people design the minigame maps if there is no Linux version of game editor available? )

I did nothing fancy to the trigger script, but just adding few more units or change to different units. I am still learning these editing stuff through the SC2 Mapster website. Of course I am happy to contribute to the community repo once I complete the maps and possibly making them more playable.

**Comment by stevenbinhu21** [comment]
@SoyGema  Never mind, I figured it out. Turns out the Linux game package version is too old to render the maps created by the current game editor (My SC2 Version is 4.3.0.64469). So using 4.0.1 or later Linux game package will render the maps with all the units just fine. And the map created either in MacOSX or Windows editor will work for PySC2 for all 3 OSs.

**Comment by SoyGema** [comment]
As this issue seems to be solved , I shall close it. 
Please, feel free to reopen if you consider necessary
